# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('device', models.CharField(choices=[(b'Phone', b'Phone'), (b'Tablet', b'Tablet'), (b'Laptop', b'Laptop')], max_length=30)),
                ('status', models.CharField(choices=[(b'Open', b'Open'), (b'Close', b'Close'), (b'Assigned', b'Assigned')], default=b'Open', max_length=30)),
            ],
        ),
    ]
